-- Example sentences from the Tanaka/Tatoeba corpus, embedded per-sense in the
-- jmdict-examples-eng build. One row per (sense, sentence pair). The sense_id btree
-- is built post-load in load.ts buildIndexes(); no full-text index here on purpose
-- (search resolves the word via the existing kanji/kana/gloss indexes, then joins).
CREATE TABLE example (
  id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sense_id  BIGINT   NOT NULL REFERENCES sense (id) ON DELETE CASCADE,
  position  SMALLINT NOT NULL,
  source    TEXT,            -- Tatoeba sentence id (source.value)
  japanese  TEXT     NOT NULL,
  english   TEXT
);
