-- Core JMdict hierarchy: entry → kanji / kana / sense → gloss, plus a tag lookup.
-- Structure only; GIN + filter indexes come in a later migration, built AFTER the
-- bulk load (index-after-load). xref deferred.

-- entry.id is JMdict's own sequence number (ent_seq), used directly as a natural key.
CREATE TABLE entry (
  id BIGINT PRIMARY KEY
);

CREATE TABLE kanji (
  id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entry_id  BIGINT   NOT NULL REFERENCES entry (id) ON DELETE CASCADE,
  position  SMALLINT NOT NULL,            -- source order within the entry; 1 = primary
  text      TEXT     NOT NULL,
  common    BOOLEAN  NOT NULL,
  tags      TEXT[]   NOT NULL DEFAULT '{}'
);

CREATE TABLE kana (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entry_id          BIGINT   NOT NULL REFERENCES entry (id) ON DELETE CASCADE,
  position          SMALLINT NOT NULL,
  text              TEXT     NOT NULL,
  common            BOOLEAN  NOT NULL,
  tags              TEXT[]   NOT NULL DEFAULT '{}',
  applies_to_kanji  TEXT[]   NOT NULL DEFAULT '{}'   -- writings this reading pairs with; {'*'} = all
);

-- part_of_speech/field/misc/dialect are controlled-vocab tag bags: array + GIN (next
-- migration), membership validated in the loader rather than via per-row FKs to `tag`.
CREATE TABLE sense (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entry_id          BIGINT   NOT NULL REFERENCES entry (id) ON DELETE CASCADE,
  position          SMALLINT NOT NULL,
  part_of_speech    TEXT[]   NOT NULL DEFAULT '{}',
  field             TEXT[]   NOT NULL DEFAULT '{}',
  misc              TEXT[]   NOT NULL DEFAULT '{}',
  dialect           TEXT[]   NOT NULL DEFAULT '{}',
  info              TEXT[]   NOT NULL DEFAULT '{}',
  applies_to_kanji  TEXT[]   NOT NULL DEFAULT '{}',
  applies_to_kana   TEXT[]   NOT NULL DEFAULT '{}'
);

-- Glosses are rows, not an array on sense: this is the text FTS (Ph2) and pgvector
-- (Ph3) will index, so it must be queryable/rankable per row.
CREATE TABLE gloss (
  id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sense_id  BIGINT   NOT NULL REFERENCES sense (id) ON DELETE CASCADE,
  position  SMALLINT NOT NULL,
  lang      TEXT     NOT NULL DEFAULT 'eng',
  text      TEXT     NOT NULL,
  type      TEXT,
  gender    TEXT
);

-- Descriptions for the tag codes used in the arrays above. The source ships one flat
-- {code: description} map for all categories, so one lookup suffices. Pure lookup, no FK.
CREATE TABLE tag (
  code         TEXT PRIMARY KEY,
  description  TEXT NOT NULL
);
